### ISSUE TITLE
"no solution found" for first and last radius station of a rectangular blade

### ISSUE THREAD

**Issue by hsteinhaus** [byuflowlab/CCBlade.jl#10]
I am trying to use CCBlade.jl for optimization of a (remote controlled) helicopter's rotor. A rotor blade usually has a rectangular shape with a constant theta over the complete blade. When solving such a blade, the function solve() presents two warnings, one at the root and one at the tip of the blade. I have added section.r to the warn statement in line 721. With a blade starting at r=0.1m and a tip radius of 0.9m I get the follwing output:

┌ Warning: ("no solution found for this section at station ", 0.1)
└ @ CCBlade /home/holger/.julia/packages/CCBlade/pJbY9/src/CCBlade.jl:721
┌ Warning: ("no solution found for this section at station ", 0.9)
└ @ CCBlade /home/holger/.julia/packages/CCBlade/pJbY9/src/CCBlade.jl:721

What is causing these warnings?Is it safe to ignore them?

The calculated  torque and thrust of the rotor (and the resulting power) seems to be in a reasonable magnitude, so I guess there is nothing too bad happening here.

**Comment by andrewning** [comment]
You can't solve all the way at the root or tip.  See the first warning in the docs: https://flow.byu.edu/CCBlade.jl/tutorial/
Those points always have zero load.  That zero load is including in the integration of thrust/torque.  So yeah it's safe to ignore it, but better would be to change your discretization so it doesn't go all the way to root/tip.
